version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 710198852569.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t aswanth:latest .
      - docker tag aswanth:latest 710198852569.dkr.ecr.us-west-2.amazonaws.com/aswanth:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 710198852569.dkr.ecr.us-west-2.amazonaws.com/aswanth:latest
